### ISSUE TITLE
Site Corrupted when I open a problem

### ISSUE THREAD

**Issue by duongnotnhan** [LQDJudge/online-judge#91]
```
SIGSEGV: invalid_state

corrupt page /problem/aplusb
site: fatal signal: Segmentation fault
site died (signal 500, exit -11)

[Go back](javascript:history.back())

Traceback (most recent call last):
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django_jinja/backend.py", line 59, in render
    return mark_safe(self._process_template(self.template.render, context, request))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django_jinja/backend.py", line 105, in _process_template
    return handler(context)
           ^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/duongnhanac/online-judge/templates/problem/problem.html", line 1, in top-level template code
    {% extends "common-content.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/online-judge/templates/common-content.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/duongnhanac/online-judge/templates/base.html", line 374, in top-level template code
    <div id="content-body">{% block body %}{% endblock %}</div>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/online-judge/templates/common-content.html", line 71, in block 'body'
    {% block comments %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/online-judge/templates/problem/problem.html", line 402, in block 'comments'
    {% include "problem/related_problems.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/online-judge/templates/problem/related_problems.html", line 14, in top-level template code
    <a href="{{url('problem_detail', problem.code)}}">{{ problem.name }}</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django_jinja/builtins/extensions.py", line 190, in _url_reverse
    return reverse(name, args=args, kwargs=kwargs, current_app=current_app)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'problem_detail' with arguments '(Undefined,)' not found. 1 pattern(s) tried: ['problem/(?P<problem>[^/]+)$']
```

**Comment by duongnotnhan** [comment]
occasionally

**Comment by duongnotnhan** [comment]
When I summit a problem
`SIGSEGV: invalid_state

trang bị sập /submission/1
site: fatal signal: Segmentation fault
site died (signal 500, exit -11)

[Go back](javascript:history.back())

Traceback (most recent call last):
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/dmojsite/lib/python3.11/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/online-judge/judge/views/submission.py", line 245, in get_context_data
    context["cases_data"] = get_cases_data(submission)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/online-judge/judge/views/submission.py", line 190, in get_cases_data
    case_data = get_problem_case(submission.problem, files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duongnhanac/online-judge/judge/utils/problem_data.py", line 323, in get_problem_case
    archive_path = os.path.join(
                   ^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by Khactrung1912** [comment]
Have you resolved this issue yet? If so, could you share your solution?

**Comment by cuom1999** [comment]
sorry about the issue. May probably fix in the latest commit: https://github.com/LQDJudge/online-judge/commit/ad73e4cdf3e97e0b4ab2096d21f794cb60bf819d
